export const GET_PROFILES_FETCHING = 'GET_PROFILES_FETCHING';
export const GET_PROFILES_FULFILLED = 'GET_PROFILES_FULFILLED';
export const GET_PROFILES_REJECTED = 'GET_PROFILES_REJECTED';

export const ADD_PROFILES_FETCHING = 'ADD_PROFILES_FETCHING';
export const ADD_PROFILES_FULFILLED = 'ADD_PROFILES_FULFILLEDD';
export const ADD_PROFILES_REJECTED = 'ADD_PROFILES_REJECTED';

export const DELETE_PROFILES_FETCHING = 'DELETE_PROFILES_FETCHING';
export const DELETE_PROFILES_FULFILLED = 'DELETE_PROFILES_FULFILLED';
export const DELETE_PROFILES_REJECTED = 'DELETE_PROFILES_REJECTED';

export const UPDATE_PROFILES_FETCHING = 'UPDATE_PROFILES_FETCHING';
export const UPDATE_PROFILES_FULFILLED = 'UPDATE_PROFILES_FULFILLED';
export const UPDATE_PROFILES_REJECTED = 'UPDATE_PROFILES_REJECTED';

export const CLEAR_PROFILES_ERROR = 'CLEAR_PROFILES_ERROR';
